<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\Sermofur.Daemon\Sermofur.Daemon.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ModelContextProtocol.Core" Version="2.2.0" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Sermofur.Tests" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
</Project>
